### ISSUE TITLE
"Error: Non-assignable model expression" in demo

### ISSUE THREAD

**Issue by bcherny** [phamductri/turn-calendar#5]
1. Click a toggle button to show a calendar
2. Press "Done"

```
Error: Non-assignable model expression: '9/1/2014' (directive: turnCalendar)
    at Error (native)
    at parentSet (http://phamductri.github.io/turn-calendar/bower_components/angular/angular.js:4507:71)
    at Object.parentValueWatch (http://phamductri.github.io/turn-calendar/bower_components/angular/angular.js:4520:23)
    at Object.Scope.$digest (http://phamductri.github.io/turn-calendar/bower_components/angular/angular.js:8090:47)
    at Object.Scope.$apply (http://phamductri.github.io/turn-calendar/bower_components/angular/angular.js:8304:24)
    at HTMLButtonElement.<anonymous> (http://phamductri.github.io/turn-calendar/bower_components/angular/angular.js:13255:17)
    at HTMLButtonElement.jQuery.event.dispatch (http://phamductri.github.io/turn-calendar/bower_components/jquery/dist/jquery.js:4409:9)
    at HTMLButtonElement.elemData.handle (http://phamductri.github.io/turn-calendar/bower_components/jquery/dist/jquery.js:4095:28)angular.js:5930 (anonymous function)angular.js:5022 (anonymous function)angular.js:8109 Scope.$digestangular.js:8304 Scope.$applyangular.js:13255 (anonymous function)jquery.js:4409 jQuery.event.dispatchjquery.js:4095 elemData.handle
```

**Comment by bcherny** [comment]
the fix is to assign `'9/1/2014'` to a scope variable, and reference that variable instead of the string literal on https://github.com/phamductri/turn-calendar/blob/master/demo/index.html#L79
